### ISSUE TITLE
Windows example

### ISSUE THREAD

**Issue by bilogic** [maunolo/rusty-vban#1]
Hi!

I'm not familiar with Rust.. yet... would this be able to work in Windows?

**Comment by maunolo** [comment]
@bilogic it should work, in fact I first developed this for windows, if you pull the repo you should be able to tests the example in the repo by running `cargo run --example mic_to_speaker` the code for the example is in the examples folder, this should route your default input to your default output, if you have a mic you will be able to hear yourself.
FYI This crate is in it's early stages so there might be bugs.

**Comment by bilogic** [comment]
Thanks let me give it a shot. VoiceMeeter doesn't work well on my system.

**Comment by bilogic** [comment]
After compiling, I got this
```
E:\temp\rusty-vban>c:cargo run --example mic_to_speaker
    Finished dev [unoptimized + debuginfo] target(s) in 1.61s
     Running `target\debug\examples\mic_to_speaker.exe`
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
Warning: Wrong source
```

It runs until I hit ctrl+c

**Comment by bilogic** [comment]
```RUST
use anyhow::Result;
use rusty_vban::{emitter};

fn main() -> Result<()> {
    std::thread::spawn(move || -> Result<()> {
        emitter::EmitterBuilder::default()
	    .ip_address("192.168.1.3")
	    .stream_name("speaker")
	    .device("VB-Audio Cable A") // Optional, default: "default"
            .build()?
            .start()?;

        Ok(())
    });

    Ok(())
}
```

The above is based on the README.MD, it doesn't stay running, and exits immediately.

Any idea what I'm getting wrong?

**Comment by maunolo** [comment]
Yeah that warning shows to me too, it means that it's receiving a stream from the a invalid source, ignoring the warning were you able to hear your default input on your default output?

**Comment by maunolo** [comment]
> ```rust
> use anyhow::Result;
> use rusty_vban::{emitter};
> 
> fn main() -> Result<()> {
>     std::thread::spawn(move || -> Result<()> {
>         emitter::EmitterBuilder::default()
> 	    .ip_address("192.168.1.3")
> 	    .stream_name("speaker")
> 	    .device("VB-Audio Cable A") // Optional, default: "default"
>             .build()?
>             .start()?;
> 
>         Ok(())
>     });
> 
>     Ok(())
> }
> ```
> 
> The above is based on the README.MD, it doesn't stay running, and exits immediately.
> 
> Any idea what I'm getting wrong?

you are running the emitter in a different thread and exiting the program after starting the thread, try running directly in the main thread if the program doesn't exits it means the stream is running, like this:
```rust
use anyhow::Result;
use rusty_vban::{emitter};

fn main() -> Result<()> {
  emitter::EmitterBuilder::default()
    .ip_address("192.168.1.3")
    .stream_name("speaker")
    .device("VB-Audio Cable A") // Optional, default: "default"
    .build()?
    .start()?;

  Ok(())
}
```

**Comment by bilogic** [comment]
1. I managed to get the emitter working, able to hear the sound on my Ubuntu (where a receptor is running) while seeing the endless `Warning: Wrong source`
2. Also found out that the endless `Warning: Wrong source` comes from the receptor, since they don't show up when I disable the rust receptor
3. With code below, I'm getting a new `Error: The requested stream type is not supported by the device.`

```RUST
use anyhow::Result;
use rusty_vban::{emitter,receptor};

fn main() -> Result<()> {
    std::thread::spawn(move || -> Result<()> {

        emitter::EmitterBuilder::default()
            .ip_address("192.168.1.3")
            .channels(2)
            .device("CABLE-A Input (VB-Audio Cable A)")
            .stream_name("example-spk")
            .build()?
            .start()?;
        
        Ok(())
    });

    receptor::ReceptorBuilder::default()
        .ip_address("192.168.1.3")
        .channels(1) 
        .device("VoiceMeeter Output (VB-Audio VoiceMeeter VAIO)") 
        .stream_name("example-mic")
        .build()?
        .start()?;
 
    Ok(())
}
```

**Comment by bilogic** [comment]
```RUST
emitter::EmitterBuilder::default()
    .ip_address("192.168.1.3")
    .channels(2)
    .device("Line 2 (Virtual Audio Cable)")
    .stream_name("example-spk")
    .build()?
    .start()?;
```    

@maunolo some updates:

1. The above works now and is meant as a drop in replacement for VoiceMeeter
2. However, `rusty-vban` behaves a little differently
3. When I use VoiceMeeter and change the volume of `Line 2`, the volume of what I hear changes
4. In contrast, when using `rusty-vban`, what I hear is always 100% no matter how I change the volume of `Line 2`
5. Any idea if this can be addressed?

**Comment by bilogic** [comment]
https://github.com/maunolo/rusty-vban/blob/d4b8769d8f41da7f25070d6f35b1abc94e746e3f/src/emitter/stream.rs#L158-L161

I suspect volume control can be implemented here, but have practically 0 ability to write rust

**Comment by maunolo** [comment]
Hey great that you were able to see it working, about the volume problem I'm not sure how to implement that to be honest, currently what I do to change the volume is I just control the volume of the source, for example I have a mic that I'm emitting the sound to another computer I just control the mic volume in the computer that is emitting, and the one that is receiving will have the same volume.

**Comment by bilogic** [comment]
@maunolo

> 1. I managed to get the emitter working, able to hear the sound on my Ubuntu (where a receptor is running) while seeing the endless `Warning: Wrong source`
> 2. Also found out that the endless `Warning: Wrong source` comes from the receptor, since they don't show up when I disable the rust receptor
> 3. With code below, I'm getting a new `Error: The requested stream type is not supported by the device.`

Thanks! I managed to solve the volume issue, seems to be something with my cables.

Any idea what I can do about `The requested stream type is not supported...`?
I'm trying to forward a microphone from machine A to machine B and machine B is the one running `rusty-vban`. From my voicemeeter VBAN UI, I can see it is a 1 channel stream.

**Comment by bilogic** [comment]
1. My receptor runs and even triggers the Windows Firewall requesting access, but terminates immediately with the overflow error. 
2. It was receiving data from this emitter https://github.com/quiniouben/vban/blob/master/src/emitter/main.c which is a 44100 Hz 2 channel PCM 16 bits stream (as read off from VoiceMeeter VBAN)
3. VoiceMeeter's VBAN was able to receive and play data from this emitter (So I take it that the emitter complies to VBAN)

Any idea?

Thank you.

```RUST
use anyhow::Result;
use rusty_vban::{receptor};

fn main() -> Result<()> {
    receptor::ReceptorBuilder::default()
        .ip_address("192.168.1.3")
        .stream_name("example-mic")
        .channels(2) 
        .device("VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)") 
        // .device("VoiceMeeter Output (VB-Audio VoiceMeeter VAIO)") 
        .build()?
        .start()?;

    Ok(())
}
```

```
cargo run --example receptor
    Finished dev [unoptimized + debuginfo] target(s) in 1.33s
     Running `target\debug\examples\receptor.exe`
thread 'main' panicked at 'attempt to add with overflow', src\protocol\header.rs:111:26
stack backtrace:
   0:     0x7ff6e9bc3bbc - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff6e9bd70fb - core::fmt::rt::Argument::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\rt.rs:138
   2:     0x7ff6e9bd70fb - core::fmt::write
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\mod.rs:1094
   3:     0x7ff6e9bc17df - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\io\mod.rs:1714
   4:     0x7ff6e9bc396b - std::sys_common::backtrace::_print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff6e9bc396b - std::sys_common::backtrace::print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff6e9bc5b5a - std::panicking::default_hook::closure$1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:269
   7:     0x7ff6e9bc57af - std::panicking::default_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:288
   8:     0x7ff6e9bc620e - std::panicking::rust_panic_with_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:705
   9:     0x7ff6e9bc60ba - std::panicking::begin_panic_handler::closure$0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:595
  10:     0x7ff6e9bc4539 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff6e9bc5e00 - std::panicking::begin_panic_handler
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
  12:     0x7ff6e9bde305 - core::panicking::panic_fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
  13:     0x7ff6e9bde3b2 - core::panicking::panic
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:117
  14:     0x7ff6e9b755d0 - rusty_vban::protocol::header::impl$1::try_from
                               at E:\temp\rusty-vban\src\protocol\header.rs:111
  15:     0x7ff6e9b78878 - rusty_vban::protocol::packet::impl$3::try_from
                               at E:\temp\rusty-vban\src\protocol\packet.rs:55
  16:     0x7ff6e9b6ef59 - rusty_vban::receptor::socket::VbanReceptorSocket::receive_packet
                               at E:\temp\rusty-vban\src\receptor\socket.rs:65
  17:     0x7ff6e9b6f5cd - rusty_vban::receptor::socket::VbanReceptorSocket::start_receive_loop<rusty_vban::receptor::impl$0::start::closure_env$0>
                               at E:\temp\rusty-vban\src\receptor\socket.rs:40
  18:     0x7ff6e9b58268 - rusty_vban::receptor::Receptor::start
                               at E:\temp\rusty-vban\src\receptor\mod.rs:38
  19:     0x7ff6e9b525a5 - receptor::main
                               at E:\temp\rusty-vban\examples\receptor.rs:6
  20:     0x7ff6e9b5103b - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  21:     0x7ff6e9b52c9e - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\sys_common\backtrace.rs:135
  22:     0x7ff6e9b51711 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\rt.rs:166
  23:     0x7ff6e9bbdbf8 - std::rt::lang_start_internal::closure$2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\rt.rs:148
  24:     0x7ff6e9bbdbf8 - std::panicking::try::do_call
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:500
  25:     0x7ff6e9bbdbf8 - std::panicking::try
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:464
  26:     0x7ff6e9bbdbf8 - std::panic::catch_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panic.rs:142
  27:     0x7ff6e9bbdbf8 - std::rt::lang_start_internal
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\rt.rs:148
  28:     0x7ff6e9b516ea - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\rt.rs:165
  29:     0x7ff6e9b526e9 - main
  30:     0x7ff6e9bdca40 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  31:     0x7ff6e9bdca40 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  32:     0x7fffa1407614 - BaseThreadInitThunk
  33:     0x7fffa31226b1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\receptor.exe` (exit code: 101)
```

**Comment by bilogic** [comment]
@maunolo 

I found the issue, u8 has range from 0-255, but +1 caused it to become 256 which resulted in the overflow exception.

**Comment by maunolo** [comment]
Oh nice I'll take a look at your PR

**Comment by maunolo** [comment]
About the error `The requested stream type is not supported...` it's a error from the cpal library, and there is two types of stream you can create for a device, input and output, I think what happened was that the device you selected for your receptor didn't supported a output stream.

**Comment by bilogic** [comment]
Yea, thanks, I managed to solved all issues already. Both speaker and mic are working. :)
